/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs.cs2236.homeworkOne;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        //App classUnderTest = new App();
       // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
